### PR TITLE
Review

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
No functional changes :slightly_smiling_face:

### CODE REVIEW

**Comment by KristjanESPERANTO** [comment]
@maxbethge Are you still maintaining this module? :slightly_smiling_face:

**Comment by maxbethge** [comment]
I got it working enough for my use although it was a bit of a hack job and uses 2 api keys to get around the quota limit.

**Comment by KristjanESPERANTO** [comment]
I like it! Thank you! 🙂

**Comment by MrJamieMcC** [comment]
> I got it working enough for my use although it was a bit of a hack job and uses 2 api keys to get around the quota limit.

Im having trouble finding the specific API keys on AccuWeather
image

**Comment by maxbethge** [comment]
You'll need to create an account and then create a new App for the `Core Weather Limited Trial` product.

image

**Comment by MrJamieMcC** [comment]
> You'll need to create an account and then create a new App for the `Core Weather Limited Trial` product.
> 
> image

Thanks for the quick response. I managed to figure it out using this video https://www.youtube.com/watch?v=KQ_nHbnAzPc

I have another side question. Both magic mirror and this module are set to use metric but this module is displaying imperial only

**Comment by maxbethge** [comment]
It looks like I didn't implement the logic to send the unit type in the call to Accuweather since it returns imperial by default and that's what I am using.

**Comment by MrJamieMcC** [comment]
Do you plan to implement such feature to use the metric? If not can you point me in the right direction and i'll make a PR

**Comment by maxbethge** [comment]
There are two urls in the node_helper.js. Based on the API documentation, adding the query param metric=true should work but I haven't had a chance to make the change or test it.

**Comment by KristjanESPERANTO** [comment]
@maxbethge: Would be nice if you would activate issues in this repository so people don't have to use this PR for troubleshooting :smiley:

**Comment by maxbethge** [comment]
@KristjanESPERANTO I enabled issues

@MrJamieMcC I updated the handling of metric units so at least with my basic config, metric units are working.

**Pull request merged**
